### ISSUE TITLE
Allow to switch to hexadecimal colour representation

### ISSUE THREAD

**Issue by ruXlab** [Yukichka/ColourGame#1]
*[ Context ]*

At the moment colour components are displayed in human-readable decimal system. While it's okay for normal people many developers may find those numbers confusing and get lost

*[ Desired result ]*

Allow to switch between hexadecimal and decimal colour representations

*[ Example ]*

`rgb(244, 116, 66)` would be represented as `#f47442`

**Comment by Yukichka** [comment]
fixed

**Comment by Yukichka** [comment]
fixed in f0195b9
